name: Formatting

on:
  push:
    branches: [main, staging]
  pull_request:
  workflow_dispatch:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        name: Set up nix
        with:
          extra_nix_config: experimental-features = nix-command flakes

      - run: nix shell nixpkgs#haskellPackages.fourmolu -c ./.github/format.sh
        name: "Run fourmolu"
